# Generated by Django 6.0.6 on 2026-06-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=32, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('refunded', 'Refunded')], default='pending_payment', max_length=20)),
                ('case_summary', models.TextField()),
                ('meeting_url', models.URLField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('consulting_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_bookings', to=settings.AUTH_USER_MODEL)),
                ('requesting_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['consulting_physician', 'scheduled_start'], name='bookings_bo_consult_2814cc_idx'), models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx')],
            },
        ),
    ]
