# Generated by Django 6.0.6 on 2026-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0002_availabilityexception_physicianavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicianprofile',
            name='license_number',
        ),
        migrations.AlterField(
            model_name='physicianprofile',
            name='license_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
