# Generated by Django 6.0.6 on 2026-06-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0003_remove_physicianprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicianavailability',
            options={'ordering': ['physician', 'weekday', 'start_time'], 'verbose_name': 'Physician Availability', 'verbose_name_plural': 'Physician Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
