# Generated by Django 6.0.6 on 2026-06-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed_requester', 'Booking confirmed - requesting physician'), ('booking_confirmed_consultant', 'Booking confirmed - consulting physician'), ('booking_reminder_24h', 'Consultation reminder - 24h'), ('booking_reminder_1h', 'Consultation reminder - 1h'), ('payment_failed', 'Payment failed')], max_length=80)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type', 'status'], name='notificatio_notific_219496_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_3db547_idx')],
            },
        ),
    ]
